# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogPath', models.CharField(max_length=255, unique=True)),
                ('baseName', models.CharField(max_length=255)),
                ('count', models.IntegerField(null=True)),
                ('featureType', models.CharField(max_length=25)),
                ('hasM', models.CharField(max_length=2)),
                ('hasZ', models.CharField(max_length=2)),
                ('hasSpatialIndex', models.CharField(max_length=2)),
                ('shapeFieldName', models.CharField(max_length=25)),
                ('shapeType', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('baseName',),
            },
        ),
        migrations.CreateModel(
            name='FeatureDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseName', models.CharField(max_length=50, unique=True)),
                ('changeTracked', models.CharField(max_length=2)),
                ('datasetType', models.CharField(max_length=25)),
                ('isVersioned', models.CharField(max_length=2)),
                ('spatialReference', models.CharField(max_length=255)),
                ('children', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('baseName',),
            },
        ),
        migrations.CreateModel(
            name='GDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseName', models.CharField(max_length=255)),
                ('catalogPath', models.CharField(max_length=255, unique=True)),
                ('workspaceType', models.CharField(max_length=25)),
                ('workspaceFactoryProgID', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('domains', models.CharField(max_length=255)),
                ('currentRelease', models.CharField(max_length=255)),
                ('connectionString', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('workspaceType',),
            },
        ),
        migrations.CreateModel(
            name='PublisherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=25)),
                ('timestamp', models.DateField(auto_now=True)),
                ('action', models.CharField(choices=[('New', 'New'), ('R', 'Replace'), ('D', 'Drop')], max_length=3)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
