# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudSync', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FClass',
            new_name='FeatureClass',
        ),
        migrations.RenameModel(
            old_name='FDataset',
            new_name='FeatureDataset',
        ),
        migrations.RenameModel(
            old_name='PLog',
            new_name='PublisherLog',
        ),
    ]
