# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-06 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineeringassignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='engineeringassignment',
            unique_together=set([('file', 'grid_cell')]),
        ),
    ]
